on:
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python3
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Create an IME dictionary file
        run: python3 main.py separeted-csv/* > ./arknights-ime-dictionary.txt
      - name: Archive created dictionary file
        uses: actions/upload-artifact@v3
        with:
          path: ./arknights-ime-dictionary.txt
