name: Create an IME dictionary file
on:
  workflow_dispatch:

jobs:
  create-ime-dict:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python3
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Create an IME dictionary file
        run: python3 create-ime-dict.py separeted-csv/* > arknights-ime-dictionary.txt
      - name: Archive created dictionary file
        uses: actions/upload-artifact@v3
        with:
          name: arknights-ime-dictionary.txt
          path: arknights-ime-dictionary.txt
